name: geomark
description: A new Flutter project.

publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2       # Use a compatible version
  local_auth: ^2.1.0       # Use a compatible version
  table_calendar: ^3.0.0    # If you're using this package for the calendar
  intl: ^0.19.0            # For date formatting
  http: ^0.14.0            # For HTTP requests
  shelf: ^1.3.0            # For server-side Dart (if needed)
  shelf_router: ^1.0.0     # For routing in shelf (if needed)
  dart_json_mapper: ^2.0.0  # For JSON mapping (if needed)
  sqlite3: ^2.0.0          # Use this package for SQLite support

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  http: ^1.2.2  # Ensure compatibility with other packages